theme: jekyll-theme-slate
title: CausaLM
description: Causal Model Explanation Through Counterfactual Language Models
github:
  amir_name: Amir Feder
  amir_url: https://github.com/amirfeder
  nadav_name: Nadav Oved
  nadav_url: https://github.com/nadavo